.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "CCBROWSE" "1" "March 2023" ""
.SH "NAME"
\fBccbrowse\fR \- Web application for browsing data from the CALIPSO and CloudSat satellites
.SH "SYNOPSIS"
\fBccbrowse create\fR \fIname\fR
.br
\fBccbrowse create \-\-help\fR
.SH "DESCRIPTION"
Create a new repository\.
.SH "ARGUMENTS"
.TP
\fBname\fR
Name of the repository\.
.SH "OPTIONS"
.TP
\fB\-\-help\fR
Print help information and exit\.
.SH "COPYRIGHT"
Copyright \(co 2012–2023 Peter Kuma\. This program is available under the terms of an MIT license\.
.SH "BUG REPORTING"
Report bugs to \fIccplot\-general@lists\.sourceforge\.net\fR\.
.SH "SEE ALSO"
\fBccbrowse\fR(1), \fBccbrowse\-import\fR(1), \fBccbrowse\-server\fR(1)
.P
Full documentation is available at \fIhttps://ccplot\.org/ccbrowse\fR and \fIhttps://github\.com/peterkuma/ccbrowse\fR\.
